version: '3'

services:

  db:
    container_name: db
    build:
      context: ./postgres
    env_file:
      - .env
    volumes:
      - ./:/sql
    ports :
      - 5432:5432

  adminer:
    build:
      context: ./adminer
    container_name: adminer
    depends_on:
      - db
    ports :
      - 8080:8080