version: '3.8'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html
    networks:
      - app-network

  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./composer/src:/var/www/html
    networks:
      - app-network
    depends_on:
      - php

  symfony:
    build:
      context: ./symfony
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/var/www/html/project
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - php
    command: php -S 0.0.0.0:8000 -t ./project/public
#    command: composer create-project symfony/skeleton project

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    external: true